### ISSUE TITLE
CloudWatch Events can now trigger step functions

### ISSUE THREAD

**Issue by bgleonard** [horike37/serverless-step-functions#49]
It looks like AWS as well as serverless now support AWS::Events::Rule to trigger Step Functions.

**Comment by horike37** [comment]
@bgleonard 
Thank you for the info!!
Do you know where that doc is? I want to knwo the link.

**Comment by bgleonard** [comment]
Yes here they are

https://serverless.com/framework/docs/providers/aws/events/cloudwatch-event/

https://aws.amazon.com/about-aws/whats-new/2017/03/cloudwatch-events-now-supports-aws-step-functions-as-a-target/

**Comment by horike37** [comment]
Thank you for the info @bgleonard.

The feature can not be implemented yet.
Because AWS CloudFromation has not supported AWS::Events::Rule to use Step Functions(SlS deploys through CloudFormation)

I sent this feature request to AWS on Twitter before as the following tweet.
https://twitter.com/horike37/status/851406651793956864

I will implemente this if that request is adopted in the future
