### ISSUE TITLE
allow S3 as source event

### ISSUE THREAD

**Issue by cicciob92** [horike37/serverless-step-functions#83]
#### This is a Feature Proposal

In my use case I need to trigger a step functions from a S3 event.
It does not seem to be supported, right?

It would be an helpful feature

**Comment by horike37** [comment]
Thank you for asking @cicciob92 :+1:  

>In my use case I need to trigger a step functions from a S3 event.
>It does not seem to be supported, right?

Yup. Not yet.

The functionality which step functions triggered by S3 event has not been supported yet on AWS end. We surely want to introduce that to this plugin if supporting on AWS CloudFormation.

Currently, here is a workaround, which allows you to leverage lambda event instead of step functions one.
https://serverless.com/blog/how-to-manage-your-aws-step-functions-with-serverless/#use-triggered-lambda-events

**Comment by brno32** [comment]
It looks like AWS now supports this natively https://docs.aws.amazon.com/step-functions/latest/dg/tutorial-cloudwatch-events-s3.html

Can this be reopened as a feature request?
