### ISSUE TITLE
Step function deployment updates code for running executions

### ISSUE THREAD

**Issue by agandhinit** [horike37/serverless-step-functions#94]
# This is a Bug Report

## Description

* What went wrong? I deployed a step functions with lambdas for the step. Whenever i make code changes to the lambda and deploy my step, already running executions pick the latest code. Causing those executions to fail. This could cause production failures on each deployment.
* What did you expect should have happened? 
Running executions should pick old code and not the recently deployed code. New executions should pick latest code.

**Comment by horike37** [comment]
Thank you for the report @agandhinit :+1: 
Sounds a good idea, but TBH we don't have any solution to solve the problem.
Do you have any idea?

In general, The Serverless Framework deploys the function code via CloudFormation and a behavior while deploying is orchestrated on AWS side, so we shouldn't add something on any feature for changing the behavior. Otherwise, it would break a consistency of deployment.

**Comment by theburningmonk** [comment]
@agandhinit one thing you could look into, is to use aliases, and see if you can point the `Resource` fields to an alias instead of just the function (which by default points to `$LATEST`). It'll require you to update the alias with each production deployment though.

**Comment by theburningmonk** [comment]
This is supported through the `useExactVersion` option. See [here](https://github.com/horike37/serverless-step-functions#blue-green-deployment) for more details.
